# vim: ts=2 sw=2 et
version: '3.6'

name: squid-proj
services:
  squid-zscaler-noauth:
    build: ./squid-zscaler
    image: localhost/squid-zscaler
    ports:
      - "4128:3128"

  squid-zscaler-auth:
    # build: ./squid-zscaler
    image: localhost/squid-zscaler
    ports:
          - "4129:3128"
    environment:
      - AUTH_USER=insights
      - AUTH_PASSWORD=test123
      - AUTH=1

  squid-classic-noauth:
    build: ./squid-classic
    image: localhost/squid-classic
    ports:
          - "3129:3128"

  squid-classic-auth:
    image: localhost/squid-classic
    ports:
          - "3128:3128"
    environment:
      - AUTH_USER=insights
      - AUTH_PASSWORD=test123
      - AUTH=1

  squid-icap-noauth:
    image: localhost/squid-classic
    ports:
          - "5129:3128"
    environment:
      - ICAP=1

  python-icap-server:
    build: ./icap-server
    image: localhost/python-icap-server
    ports:
          - "13440:13440"
  tcpdump:
    image: corfr/tcpdump
    command: "-i any port 13440"
